@MicroservicioLogin_HostAddress = http://localhost:5032
@email = test@test.com
@contrasena = 1234
@refreshToken = BhdwxYvDpXtavAWaf27V47FQsoUX2PSiG0B3Gr1Nvx1NKIqO4P0h6SCkjVSHEbdzeND+P5c0qJ+LjS6o7qwkTg==
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRXN0dWRpYW50ZSIsImp0aSI6Ijk1NjU2ZjA3LWVjOGItNDllZC05ZDAxLTJhMTY1OGQ0MTgxMCIsImV4cCI6MTc5MDY1NDIzMiwiaXNzIjoiTWljcm9zZXJ2aWNpb0xvZ2luIiwiYXVkIjoiTWljcm9zZXJ2aWNpb0xvZ2luIn0.HFy7HAGMSkFiPJnoIyXPCWIM_CoeGJLRGvwVHBeqpdU

### Login
POST {{MicroservicioLogin_HostAddress}}/login
Email: {{email}}
Contrasena: {{contrasena}}

###

### Renovar tokens
POST {{MicroservicioLogin_HostAddress}}/refresh
RefreshToken: {{refreshToken}}

###

### Validar access token
POST {{MicroservicioLogin_HostAddress}}/validate
Authorization: Bearer {{accessToken}}
